### ISSUE TITLE
No way to export and save sqlite database

### ISSUE THREAD

**Issue by k----n** [MeasureOSS/Measure#118]
Could be a possible enhancement feature

**Comment by stuartlangridge** [comment]
I don't think I understand what this means? The sqlite database is already "exported"; it's built as part of the makedash process, so whoever's running that is welcome to copy it somewhere else as well as a backup. I don't think it should be downloadable from the web UI, so if that's what this means then can you explain some of the reasoning for that suggestion/

**Comment by k----n** [comment]
I was thinking of people who were less technical that still wanted the database for analytic purposes, but then they could just ask the admin.
