### ISSUE TITLE
Nothing should be shown if an organization has 0 members (currently/who have since left)

### ISSUE THREAD

**Issue by k----n** [MeasureOSS/Measure#126]
It should display an error message that says users need to be added instead of displaying a dashboard.

**Comment by stuartlangridge** [comment]
I'm not sure I agree with this; dashboards contain historical data, so if there ever _was_ anyone in that org, the page is still useful. If an org does not and never did have any members then I don't think we generate a page for it? But I might be wrong about that.

Anyway, @jeremy-lq may have thoughts on whether a page for an org should be created even if that org currently has no members.

**Comment by k----n** [comment]
Yes, a page is generated for an org where there were never any members in it.

Another issue I've noticed is that for pages where there are many repos, there are still links to a repo even though the stats can be from any repo under the org.

E.g.
On index, Open Issues panel has 'issues' link that goes to the repo with the most open issues?
Not sure if that's a feature or bug?
Links to the same repo are also present in these panels: Issues open and closed this month, PRs open and closed this month, PRs accepted and rejected this month
