### ISSUE TITLE
Configurable start/end dates for organization attribution

### ISSUE THREAD

**Issue by irabinovitch** [MeasureOSS/Measure#17]
Currently when attributing a contributor to an organization Measure assumes that the start day is today.  Similarly when setting an end date it is assumed the end date is TODAY.

Ideally we should be able to back date organization start / end dates, since we may be importing a repo with a great deal of history.

**Comment by stuartlangridge** [comment]
Fixed as per https://github.com/MeasureOSS/Measure/commit/25fc903804dc55592204159624e6dd3a8ccc9a2b which allows setting any start and end date for a contributor in an org.
