### ISSUE TITLE
Add to Org widget - dates don't work as expected

### ISSUE THREAD

**Issue by jeremy-lq** [MeasureOSS/Measure#21]
The Start date/End date functionality doesn't work in Firefox (Linux/v56). The widget displays some odd behavior in general in Chrome and Firefox.

**Comment by stuartlangridge** [comment]
What does "odd behaviour" mean? Does this fix it?

**Comment by jeremy-lq** [comment]
The widget sometimes resizes in ways that make it unusable, pasting into the Org box breaks the widget, etc. I'll test with the latest commit and either close or get some screenshots.

**Comment by irabinovitch** [comment]
Haven't been able to repro the org name field issues in a few days.  It used to be that if you pasted  text in there the box would disappear or resize smaller. Will grab a screenshot if i see it again.

**Comment by jeremy-lq** [comment]
This has been fixed.
