### ISSUE TITLE
Organization issues

### ISSUE THREAD

**Issue by jeremy-lq** [MeasureOSS/Measure#27]
When adding a contributor to an org:

1) The list is not sorted, which makes it difficult to scan.
2) The list is not de-duped - are there multiple orgs with the same name?
3) We should auto complete existing orgs in the new org box, to limit slight misspellings/accidental dupes.

**Comment by stuartlangridge** [comment]
There aren't accidental duplicates; if you type in the name of an org that already exists, it quietly uses the already existing one rather than creating a new one. We _could_ autocomplete as well, I suppose, but autocompleting while typing is a bit awkward. I'll look into it.

**Comment by stuartlangridge** [comment]
Autocompletion and sorting in https://github.com/MeasureOSS/Measure/commit/01736b880f897aa7e75a525c2fe07f1f71e20709. Not closed yet because there still may be ways to create duplicates which aren't yet identified.

**Comment by stuartlangridge** [comment]
I don't think there are ways to create duplicates, now. Leaving open for the team to confirm that they're happy with the way it works before closing.

**Comment by jeremy-lq** [comment]
Will verify. What's the recommended path for removing existing dupes?

**Comment by jeremy-lq** [comment]
Haven't been able to create duplicates since https://github.com/MeasureOSS/Measure/commit/01736b880f897aa7e75a525c2fe07f1f71e20709.
