### ISSUE TITLE
Open PRs / Open Issues Age

### ISSUE THREAD

**Issue by jeremy-lq** [MeasureOSS/Measure#28]
On the Open PRs / Open Issues widgets we should show the mean/median/95th for how long they've been open.

**Comment by stuartlangridge** [comment]
I... don't think I know how to calculate this. It's a line graph, showing how many PRs were open that month. It doesn't have mean statistics, does it? Am I misunderstanding something here? Happy to have this explained to me in words of one syllable so I get it.

![image](https://user-images.githubusercontent.com/4356350/33234454-0a62df88-d21f-11e7-9db5-0ea7b43ebb73.png)

**Comment by jeremy-lq** [comment]
In the example screenshot you've posted, there are 9 open issues. We'd like to know (as a number somewhere, but probably not as part of the actual graph itself) the mean/median/95th duration those have been open.

**Comment by jeremy-lq** [comment]
Looks good for issues. Should also be reflected for PRs.

**Comment by stuartlangridge** [comment]
(done. good catch)
