### ISSUE TITLE
Users not in an org generation

### ISSUE THREAD

**Issue by jeremy-lq** [MeasureOSS/Measure#33]
`Users not in an org` contains people we know the name of but don't have any relevant data for. These should be excluded.

**Comment by irabinovitch** [comment]
I'm curious how we learned their name if they don't have commits, issues, etc?

**Comment by jeremy-lq** [comment]
We initially thought this was ghcrawler pulling in extraneous data, but a closer look indicates this may not actually be the case. Researching further.

**Comment by stuartlangridge** [comment]
I _think_ this should now be fixed. Please re-open if not.
