### ISSUE TITLE
New Widget: PRs and Issues over time

### ISSUE THREAD

**Issue by jeremy-lq** [MeasureOSS/Measure#47]
New widget for contributor and org pages: line graph with PRs and Issues over time.

**Comment by stuartlangridge** [comment]
I'm not sure what this is actually measuring? Can you give an example or a more detailed description?

**Comment by stuartlangridge** [comment]
Note: this is the existing issuesStackChart (and prsStackChart); they just need to be applied to contributor and org and team pages as well.
