### ISSUE TITLE
Decide on an order for widgets

### ISSUE THREAD

**Issue by stuartlangridge** [MeasureOSS/Measure#57]
Think up what order we want widgets to be in, and rename them accordingly as 000_widgetname.js so they're in order.

**Comment by jeremy-lq** [comment]
First shot: https://github.com/MeasureOSS/Measure/commit/3a8b074b427c16008ea259eef27a73d93be421a7

Feedback is welcome.

**Comment by jeremy-lq** [comment]
https://github.com/MeasureOSS/Measure/commit/01ac151b4a63f6eeb5c76712d037dbf040887709 and https://github.com/MeasureOSS/Measure/commit/79ecff96543716ff19ed31ae9bf7270e59ba9e05

**Comment by jeremy-lq** [comment]
I think we're in a good place for initial ordering. Closing this and we can evaluate further changes on an individual basis.
