### ISSUE TITLE
Org queries don't all take account of joined/left dates

### ISSUE THREAD

**Issue by stuartlangridge** [MeasureOSS/Measure#62]
For example prCount (and prsAcceptedVsRejected) just basically do `db.prs.count()`, which is inflated to `db.prs.count(login: {in: [orguser1, orguser2, orguser3]})` by the query framework. But users may have joined and left the org; if `orguser2` left in 2016, then we don't want PRs they did after that to be attributed to the org they're no longer in. This is going to require the query framework to be quite a bit cleverer for orgs.

**Comment by stuartlangridge** [comment]
This is prooooobably fixed by the above commit, but it's pretty invasive, so leaving this open in case anything weird and unexpected happens to the data.

**Comment by jeremy-lq** [comment]
https://github.com/MeasureOSS/Measure/commit/b2148ff5f315a5e23c3790718c82c99b72d529aa does appear to have fixed this.
