### ISSUE TITLE
Use a salt in PHP crypt

### ISSUE THREAD

**Issue by stuartlangridge** [MeasureOSS/Measure#63]
`PHP message: PHP Notice:  crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash. in api.php on line 174`

**Comment by jeremy-lq** [comment]
Note that once this is fixed we can remove the web server + PHP requirement and replace with:
`docker run --name nginx-measure  -p 443:443 -p 80:80 -v /path/to/Measure/dashboard:/var/www/html -d boxedcode/alpine-nginx-php-fpm`
