### ISSUE TITLE
How to debug issue with makedash.js

### ISSUE THREAD

**Issue by joedborg** [MeasureOSS/Measure#75]
I'm getting the following issue with 

```
Problem message:
  WARNING: there seem to be no database entries for some of your 
  repositories. You may need to wait a little longer for the data 
  to arrive before these dashboards can be generated.
  Alternatively, you may need to tell the crawler to fetch these 
  data. Run the following commands in the ghcrawler-cli folder
```

I've also run the commands it suggests.  I guess there's an issue populating the initial data, where can I check?

Thanks,
Joe

**Comment by jeremy-lq** [comment]
Have you checked the [ghcrawler dashboard](https://github.com/Microsoft/ghcrawler#browser-dashboard) to ensure the crawl has completed?

**Comment by jeremy-lq** [comment]
Sounds like this is a ghcrawler issue. It may be related to tokens, but I've found the logs are generally useful for debugging.

**Comment by joedborg** [comment]
There's nothing obvious in the crawler log (lots of HTTP 200s).  I'll keep digging and see what I can find / log a bug with `ghcrawler`.
