### ISSUE TITLE
Removing my_organizations from config causes problems

### ISSUE THREAD

**Issue by ralight** [MeasureOSS/Measure#85]
````
makedash.js:49
            for (i=0; i<options.userConfig.my_organizations.length; i++) {
                                                           ^
TypeError: Cannot read property 'length' of undefined
````

I didn't know what to put in the `my_organizations` setting, so I removed it. User error perhaps, but I thought it was worth mentioning - maybe some extra info in the config example, or setting a default?

**Comment by stuartlangridge** [comment]
Fixed; thank you!
