### ISSUE TITLE
Glitches on Total open PRs graph

### ISSUE THREAD

**Issue by ralight** [MeasureOSS/Measure#90]
![glitch](https://user-images.githubusercontent.com/79578/38644883-0a7de324-3dda-11e8-9366-3c48feb4d20a.png)

It doesn't seem like they should happen. Looks like it's a New Year problem. There might be a similar problem on First PR response, but I'm less sure of that.

**Comment by stuartlangridge** [comment]
This is, extremely irritatingly, down to one's definition of what a "week" is. We may need to apply some heuristics here to smooth the curve around week 53 or week 0.
