### ISSUE TITLE
Organisation membership

### ISSUE THREAD

**Issue by perploug** [MeasureOSS/Measure#95]
Reading through the code I realised that you do not seem to use the Github Organisation membership in your queries, but instead use you sqllite based membership - is there a reason for that? as it doesn't really scale with 1000s of employees :) 

Is there a way to simply use the membership of a specific org to determin if the contributor is internal or external - or is that a limitation in the ghcrawler data?

**Comment by irabinovitch** [comment]
@perploug Automating this would be great, but I'm not sure github org is the right way to do it. We've fund that many of our community members do not publicly display their memberhips on their github profile, or are members of multiple github orgs.

**Comment by perploug** [comment]
@irabinovitch thats interesting - how would hiding org membership work on github? I do not see an option anywhere for this. 

Multiple org memberships would not be a problem if you look at this in the context of a org or a repo as that would only be concerning a single org.

**Comment by perploug** [comment]
Never mind I see the option now, that makes sense, thanks for pointing that out
